name: FiveZeroFive
favicon: null
layout_spectrum: 0.2466173053253442
typography_spectrum: 0.4878152566961944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#8f897b'
    - '#ece444'
    - '#e87481'
    - '#98242d'
  brandStrength: 0.25018952088430524
  lightness: 0.9356007557362318
  saturation: 0.8043290039058775
  rhythmicContrast: 0.17023964086547494
purpose: []
