name: FiveZeroFive
favicon: null
layout_spectrum: 0.74292
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bec6bb'
    - '#90867d'
    - '#605247'
    - '#2e2617'
    - '#fdc687'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
